services:
  php:
    container_name: iw-php
    build:
      context: .
      dockerfile: conf/php/Dockerfile
    restart: on-failure
    ports:
      - 50180:80
    volumes:
      - ./src/html:/var/www/html
      - ./src/bean:/var/www/bean
      - ./src/elfo:/var/www/elfo
      - ./conf/apache:/etc/apache2
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"